version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Configurer Maven
          command: mvn -version
      - run:
          name: Compiler le projet
          command: mvn clean compile
      - run:
          name: Exécuter les tests
          command: mvn test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
